set_property IOSTANDARD LVCMOS33 [get_ports {led_enb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports enb_led]
set_property PACKAGE_PIN G17 [get_ports {led_enb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enb[2]}]
set_property IOSTANDARD SSTL135 [get_ports {sw_in[2]}]
set_property PACKAGE_PIN J15 [get_ports {led_enb[1]}]
set_property PACKAGE_PIN F15 [get_ports {led_enb[0]}]
set_property PACKAGE_PIN M5 [get_ports {sw_in[2]}]
set_property PACKAGE_PIN G18 [get_ports {sw_in[1]}]
set_property PACKAGE_PIN H14 [get_ports enable]
set_property PACKAGE_PIN E18 [get_ports enb_led]
set_property PACKAGE_PIN H18 [get_ports {sw_in[0]}]
set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { clk }]
set_property INTERNAL_VREF 0.675 [get_iobanks 34]